### PR TITLE
fix: fix field alignment to avoid panics on 32bit OSes

### LINKED ISSUE #43: bug: Panic on 32-bit platforms
There are a number of field alignment issues in this package, which cause panics on 32-bit platforms. I built a quick Docker image to run the tests:

_Dockerfile.test:_
```Dockerfile
FROM golang:1.22

WORKDIR /app

COPY . .
```

```console
$ docker build --platform=linux/386 -t test_32bit -f Dockerfile.test .
[...]
$ docker run --platform=linux/386 --rm test_32bit go test ./...
?       github.com/hack-pad/hackpadfs/fstest    [no test files]
?       github.com/hack-pad/hackpadfs/internal/mounttest        [no test files]
?       github.com/hack-pad/hackpadfs/internal/assert   [no test files]
?       github.com/hack-pad/hackpadfs/internal/pathlock [no test files]
?       github.com/hack-pad/hackpadfs/keyvalue/blob     [no test files]
--- FAIL: TestChmod (0.00s)
panic: unaligned 64-bit atomic operation [recovered]
        panic: unaligned 64-bit atomic operation

goroutine 23 [running]:
testing.tRunner.func1.2({0x81d5b80, 0x82378b0})
        /usr/local/go/src/testing/testing.go:1631 +0x2a3
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1634 +0x434
panic({0x81d5b80, 0x82378b0})
        /usr/local/go/src/runtime/panic.go:770 +0x103
runtime/internal/atomic.panicUnaligned()
        /usr/local/go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0x886609c)
        /usr/local/go/src/runtime/internal/atomic/atomic_386.s:225 +0x10
github.com/hack-pad/hackpadfs/keyvalue/blob.(*Bytes).Len(0x8866090)
        /app/keyvalue/blob/bytes.go:56 +0x26
[...]
```

This particular failure is due to the `blob.Bytes` type, which is misaligned:

```go
type Bytes struct {
	bytes  []byte		// 24 bytes on 64-bit, 12 bytes on 32-bit
	length int64		// 8 bytes
	mu     *sync.Mutex	// 8 bytes on 64-bit, 4 bytes on 32-bit
}
```

If we run `fieldalignment` on this, we see (on 64-bit):

```console
$ fieldalignment ./keyvalue/blob/  
/Users/hairyhenderson/go/src/github.com/hack-pad/hackpadfs/keyvalue/blob/bytes.go:23:12: struct with 40 pointer bytes could be 16
```

And on 32-bit:
```console
$ go install golang.org/x/tools/go/analysis/passes/fieldalignment/cmd/fieldalignment@latest
[...]
$ fieldalignment ./keyvalue/blob/  
/app/keyvalue/blob/bytes.go:23:12: struct with 24 pointer bytes could be 8
```

So it's not optimally-aligned, but that's not actually the root issue. The root issue is [a known bug on 32-bit systems on many `atomic.*` functions](https://pkg.go.dev/sync/atomic#pkg-note-BUG), namely:

> On ARM, 386, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically via the primitive atomic functions (types [Int64](https://pkg.go.dev/sync/atomic#Int64) and [Uint64](https://pkg.go.dev/sync/atomic#Uint64) are automatically aligned). [...] 

Thankfully, fixing this automatically with `fieldalignment` works fine (it moves `mu` to the beginning so we get a 32-byte or 16-byte offset before `length`, thus aligning `length` on a 64-bit/8-byte boundary as it needs to be).

I'm going to issue a PR that enables the `fieldalignment` linter (which is built into the `govet` linter in golangci-lint), and fixes the found problems.

### PR DESCRIPTION
**Pull request by hairyhenderson**
Fixes #43

To solve this, I:
- enabled the `fieldalignment` linter (which is a sub-linter of `govet`)
- ran the `fieldalignment -fix` command to fix misaligned structs that were non-obvious
- switch from using e.g. `int64` + `atomic.StoreInt64` to using `atomic.Int64` (etc) and because of this...
- drop Go 1.18 support, and require Go 1.19+ (where the new atomic types were introduced)
- added a new CI job to test in a 32-bit container (so far just Intel 386, which should catch the same bugs as arm32/etc)
- added some new tests to cover `keyvalue/blob.Bytes`, which was what was giving me trouble initially

### CODE REVIEW

File: keyvalue/blob/bytes.go [hunk 1]
```diff
@@ -16,14 +16,14 @@ var (
 		SetBlob
 		GrowBlob
 		TruncateBlob
-	} = &Bytes{}
+	} = (*Bytes)(nil)
```
Comment (hairyhenderson) [inline keyvalue/blob/bytes.go:19]: This change isn't related, but is a (very mild) refactoring that lets the compiler remove this (I think we save 8 bytes of memory) - it's a little more idiomatic to do it this way.

File: keyvalue/file.go [hunk 2]
```diff
@@ -33,12 +33,12 @@ type file struct {
 }
 
 type fileData struct {
-	runOnceFileRecord
+	fs   *FS
+	path string // path is stored as the "key", keeping it here is for generating hackpadfs.FileInfo's
+
 	modeOverride    *hackpadfs.FileMode
```
Comment (JohnStarich) [inline keyvalue/file.go:39]: A tiny nit: Since the ordering isn't as flexible anymore and gofmt likes to align the names/types, let's delete the blank lines between fields for all of the realigned structs.

The runOnceFileRecord one in particular is a bit weird. In a future PR, I imagine it'd be worth a small refactor to group the sync.Once and value in a common type. Go 1.21's `sync.OnceValue` looks promising.

File: keyvalue/record.go [hunk 3]
```diff
@@ -112,34 +112,34 @@ func (b *BaseFileRecord) Sys() interface{} {
...
-	dirNamesErr  error
-	dirNamesOnce sync.Once
+	dirNames []string
 
 	size     int64
-	sizeOnce sync.Once
-
-	mode     hackpadfs.FileMode
-	modeOnce sync.Once
+	dataDone atomic.Int64
```
Comment (JohnStarich) [inline keyvalue/record.go:127]: If I remember right, dataDone behaves more like a `bool` but the atomic package didn't have those operations available at the time. Let's try to use `atomic.Bool` here.

File: mount_test.go [hunk 4]
```diff
@@ -13,9 +13,9 @@ func TestStripErrPathPrefix(t *testing.T) {
 	someError := errors.New("some error")
 	for _, tc := range []struct {
 		err          error
+		expectErr    error
 		name         string
 		mountSubPath string
-		expectErr    error
```
Comment (JohnStarich) [inline mount_test.go:18]: Same as fstest, if feasible let's avoid reordering the table driven test case types for better readability.

File: tar/bufferpool.go [hunk 5]
```diff
@@ -7,40 +7,41 @@ import (
...
 	}
+	p.size.Store(bufferSize)
 	p.addBuffer() // start with 1 buffer, ready to go
 	return p
 }
 
 func (p *bufferPool) addBuffer() {
 	for {
-		count := atomic.LoadInt64(&p.count)
+		// count := atomic.LoadInt64(&p.count)
```
Comment (JohnStarich) [inline tar/bufferpool.go:34]: Oops, stray comment?
```suggestion
```

**Review by JohnStarich — CHANGES_REQUESTED** [review]
I'm not very experienced with these kinds of alignment issues, so I'm definitely open to a bit of discussion on how to handle these.

If at all possible, my strong preference is to maintain field ordering in the table driven test case types to keep it easier to quickly read and understand the tests. Of course if the tests fail, we'll need to do something else :thinking:

**Comment by hairyhenderson** [comment]
> If at all possible, my strong preference is to maintain field ordering in the table driven test case types

I can revert the test files, no big deal.

File: .github/workflows/ci.yml [hunk 6]
```diff
@@ -40,3 +39,13 @@ jobs:
       env:
         COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         COVERAGE_VERSION: 1.19
+  test32bit:
+    runs-on: ubuntu-latest
```
[the remark this answers is not in the document]
Comment (hairyhenderson) [reply .github/workflows/ci.yml:43]: GitHub Actions doesn't provide 32-bit runners so the most reliable way to run as 32-bit is to use QEMU and Docker.

But, if this can be reproduced on a 64-bit runner simply running with GOARCH=386 that'd be fine. I'll mess with that and see if it works.

File: fstest/file.go [hunk 7]
```diff
@@ -94,12 +94,12 @@ func TestFileReadAt(tb testing.TB, o FSOptions) {
...
 	for _, tc := range []struct {
+		expectErr   error
 		description string
-		bufSize     int
+		expectBuf   string
 		off         int64
+		bufSize     int
 		expectN     int
-		expectBuf   string
-		expectErr   error
```
[the remark this answers is not in the document]
Comment (hairyhenderson) [reply fstest/file.go:102]: If changing field ordering causes a struct to be unreadable, then I think we need some comments instead 😉

But, I'll revert and ignore these changes.

File: keyvalue/file.go (hunk 2 above)
Comment (hairyhenderson) [reply keyvalue/file.go:39]: > Since the ordering isn't as flexible anymore [...]

To be clear, the ordering was never flexible - alignment has always mattered...

I had the same thought about `sync.OnceValue`, but I didn't want to update Go too far, partly because the linter catches more things and I've spent way too much time on this already... A future PR sounds good.

I'll delete blank lines.

File: keyvalue/record.go (hunk 3 above)
Comment (hairyhenderson) [reply keyvalue/record.go:127]: worth it, sure.

File: .github/workflows/ci.yml (hunk 6 above)
[the remark this answers is not in the document]
Comment (hairyhenderson) [reply .github/workflows/ci.yml]: ok, it was a bit more than setting `GOARCH` - I needed to tell `setup-go` to install the 386 version, but it works:

```
--- FAIL: TestChmod (0.00s)
panic: unaligned 64-bit atomic operation [recovered]
	panic: unaligned 64-bit atomic operation
```

**Comment by hairyhenderson** [comment]
@JohnStarich thanks for the feedback, I think I've addressed it all - please have another look!

(I'm not sure why coveralls thinks the coverage decreased - I added new tests... ¯\\\_(ツ)_/¯)

File: .github/workflows/ci.yml [hunk 8]
```diff
@@ -19,24 +19,24 @@ jobs:
...
-        - platform: windows-latest
-          go: 1.19.x
+        platform: [ ubuntu-latest, windows-latest, macos-latest ]
+        version: [ v1.19.x ]
+        goarch: [ amd64, '386' ]
+        exclude:
+          - platform: macos-latest
+            goarch: '386'
+          - platform: windows-latest
+            goarch: '386'
```
Comment (JohnStarich) [inline .github/workflows/ci.yml:29]: This is great, thanks!

We may want to reduce the matrix a bit to a single 32 bit runner in the future, assuming we can prove the effective coverage is the same. As someone who's worked with 32 bit arch's more than me, do you foresee any problems with only validating those arch's on a single platform and Go version?

File: .github/workflows/ci.yml (hunk 6 above)
[the remark this answers is not in the document]
Comment (JohnStarich) [reply .github/workflows/ci.yml]: Very interesting, I wonder why the env var was insufficient :thinking: On my Linux machine it panicked as expected.

File: fstest/file.go (hunk 7 above)
[the remark this answers is not in the document]
Comment (JohnStarich) [reply fstest/file.go]: :wink: 

It's not that it became unreadable per se, but a tad less. Thank you.

File: keyvalue/file.go (hunk 2 above)
Comment (JohnStarich) [reply keyvalue/file.go:38]: I hear ya, I was referring to the linter gating things now. Less flexible in the eyes of CI, if you will.

**Review by JohnStarich — APPROVED** [review]
Thanks again! Super appreciate the thought and time you put into this.

I did have one question about the future of maintaining 32 bit support here, since I'm not as well versed in field alignment issues like this. https://github.com/hack-pad/hackpadfs/pull/44#discussion_r1650145979

File: fstest/file.go [hunk 9]
```diff
@@ -653,6 +654,7 @@ func TestFileSync(tb testing.TB, o FSOptions) {
 	assert.NoError(tb, file.Close())
 }
 
+//nolint:govet
```
[the remark this answers is not in the document]
Comment (hairyhenderson) [reply fstest/file.go:657]: It's at least awkward in the golangci config, if not impossible - it lets you disable whole linters (i.e. `govet` in this case), but not sub-linters like `fieldalignment`. 

If you want to avoid linting all tests with `govet`, then that's an option, but...

File: Makefile [hunk 10]
```diff
@@ -2,6 +2,7 @@ BROWSERTEST_VERSION = v0.7
 LINT_VERSION = 1.50.1
 GO_BIN = $(shell printf '%s/bin' "$$(go env GOPATH)")
 SHELL = bash
+ENABLE_RACE = true
```
[the remark this answers is not in the document]
Comment (hairyhenderson) [reply Makefile:5]: 🤦‍♂️ good catch - that can be deleted

File: .github/workflows/ci.yml (hunk 8 above)
Comment (hairyhenderson) [reply .github/workflows/ci.yml:29]: The only reason I didn't also add 32-bit ARM as well is that it's a huge pain to do (without Docker) in GitHub Actions, because the GitHub-hosted runners are all AMD64 currently (ARM64 is coming this fall maybe?).

Another option is to use a self-hosted runner, and I happen to be deep in that rabbit-hole right now (https://github.com/hairyhenderson/gomplate/pull/2126) and it's going about as well as you'd expect (i.e. not at all well).

For this particular class of bug any 32-bit platform will generally do, but there are other classes of bugs that can crop up only on 32-bit ARM CPUs. Somewhat ironically it's extremely rare to run into 32-bit Intel systems except for niche embedded use-cases, but it's still quite common to run into 32-bit ARM given the massive proliferation of older Raspberry Pi-type systems and routers strewn across the IoT landscape.

File: Makefile [hunk 11]
```diff
@@ -31,14 +32,25 @@ test-deps:
...
+# only use the race detector on supported architectures
+race_goarches := 'amd64' 'arm64'
+ifeq (,$(findstring '$(GOARCH)',$(race_goarches)))
+TEST_ARGS=
+export CGO_ENABLED=0
+else
+TEST_ARGS=-race
+# the race detector needs cgo (at least on Linux and Windows, and macOS until Go 1.20)
+export CGO_ENABLED=1
+endif
```
[the remark this answers is not in the document]
Comment (hairyhenderson) [reply Makefile:44]: I was already in the midst doing a similar thing for gomplate so it at least wasn't a _new_ kind of pain 😅

It probably isn't always true, but races tend to happen in the same way on all platforms, so I wouldn't be too worried here.
